Repository MikeSchulze/gdUnit4, pull requests merged in 2024-08, with the labels that each got.

#555 GD-553: Add missing test coverage for `get_child` and `get_node`
  addons/gdUnit4/test/GdUnitTestSuiteTest.gd
Labels: Exclude from release nodes

#557 Update GdUnit4 to work with Godot 4.3 release
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/ci-dev.yml
  .github/workflows/ci-pr-publish-report.yml
  .github/workflows/ci-pr.yml
  README.md
  addons/gdUnit4/plugin.cfg
  addons/gdUnit4/src/GdUnitSceneRunner.gd
  addons/gdUnit4/src/core/GdUnitSceneRunnerImpl.gd
  addons/gdUnit4/src/core/parse/GdFunctionDescriptor.gd
  addons/gdUnit4/src/mocking/GdUnitMockBuilder.gd
  addons/gdUnit4/src/update/assets/fonts/static/RobotoMono-Bold.ttf.import
  addons/gdUnit4/src/update/assets/fonts/static/RobotoMono-BoldItalic.ttf.import
  addons/gdUnit4/src/update/assets/fonts/static/RobotoMono-ExtraLight.ttf.import
  addons/gdUnit4/src/update/assets/fonts/static/RobotoMono-ExtraLightItalic.ttf.import
  addons/gdUnit4/src/update/assets/fonts/static/RobotoMono-Italic.ttf.import
  addons/gdUnit4/src/update/assets/fonts/static/RobotoMono-Light.ttf.import
  addons/gdUnit4/src/update/assets/fonts/static/RobotoMono-LightItalic.ttf.import
  addons/gdUnit4/src/update/assets/fonts/static/RobotoMono-Medium.ttf.import
  addons/gdUnit4/src/update/assets/fonts/static/RobotoMono-MediumItalic.ttf.import
  addons/gdUnit4/src/update/assets/fonts/static/RobotoMono-Regular.ttf.import
  addons/gdUnit4/src/update/assets/fonts/static/RobotoMono-SemiBold.ttf.import
  addons/gdUnit4/src/update/assets/fonts/static/RobotoMono-SemiBoldItalic.ttf.import
  addons/gdUnit4/src/update/assets/fonts/static/RobotoMono-Thin.ttf.import
  addons/gdUnit4/src/update/assets/fonts/static/RobotoMono-ThinItalic.ttf.import
  addons/gdUnit4/test/core/GdUnitSceneRunnerInputEventTest.gd
  addons/gdUnit4/test/core/GdUnitSceneRunnerTest.gd
  addons/gdUnit4/test/core/parse/GdFunctionDescriptorTest.gd
  addons/gdUnit4/test/core/parse/GdScriptParserTest.gd
  addons/gdUnit4/test/mocker/GdUnitMockBuilderTest.gd
  addons/gdUnit4/test/mocker/GdUnitMockerTest.gd
  gdUnit4.csproj
  project.godot
Labels: bug

#556 GD-554: Adding support for touch screen input event testing to `GdUnitSceneRunner`
  README.md
  addons/gdUnit4/src/GdUnitSceneRunner.gd
  addons/gdUnit4/src/core/GdUnitSceneRunnerImpl.gd
  addons/gdUnit4/src/core/GdUnitTools.gd
  addons/gdUnit4/src/core/assets/touch-button.png
  addons/gdUnit4/src/core/assets/touch-button.png.import
  addons/gdUnit4/test/core/GdUnitSceneRunnerInputEventTest.gd
  addons/gdUnit4/test/core/GdUnitSceneRunnerTest.gd
  addons/gdUnit4/test/core/resources/scenes/drag_and_drop/DragAndDropControl.gd
  addons/gdUnit4/test/core/resources/scenes/drag_and_drop/DragAndDropControl.tscn
  addons/gdUnit4/test/core/resources/scenes/drag_and_drop/DragAndDropTestScene.gd
  addons/gdUnit4/test/core/resources/scenes/drag_and_drop/DragAndDropTestScene.tscn
  addons/gdUnit4/test/mocker/resources/scenes/TestScene.gd
  addons/gdUnit4/test/mocker/resources/scenes/TestScene.tscn
Labels: enhancement

#560 GD-559: add inspector directory collapse toggling
  addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd
Labels: bug
