Repository MikeSchulze/gdUnit4, pull requests merged in 2024-07, with the labels that each got.

#530 GD-529: Fix null value access in the inspector.
  .github/ISSUE_TEMPLATE/bug_report.yml
  addons/gdUnit4/plugin.cfg
  addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd
Labels: bug, UI

#532 GD-531: Fix `assert_not_yet_implemented` reports the wrong line number
  addons/gdUnit4/src/GdUnitAssert.gd
  addons/gdUnit4/src/GdUnitTestSuite.gd
  addons/gdUnit4/src/asserts/GdUnitAssertImpl.gd
  addons/gdUnit4/test/asserts/GdUnitAssertImplTest.gd
Labels: bug

#536 GD-533: Fixes script error in `TestSuiteTemplate` when Godot was installed for the first time
  addons/gdUnit4/src/ui/templates/TestSuiteTemplate.gd
Labels: bug

#538 GD-537: Fix comparing objects containing built-in script type members
  addons/gdUnit4/src/core/GdObjects.gd
  addons/gdUnit4/test/core/GdObjectsTest.gd
  addons/gdUnit4/test/core/resources/scenes/SceneWithEmbeddedScript.tscn
Labels: bug

#534 Improve settings UI
  addons/gdUnit4/src/core/GdUnitSettings.gd
  addons/gdUnit4/src/core/GdUnitTestSuiteScanner.gd
  addons/gdUnit4/src/ui/settings/GdUnitSettingsDialog.gd
  addons/gdUnit4/src/ui/settings/GdUnitSettingsDialog.tscn
  addons/gdUnit4/test/core/GdUnitSettingsTest.gd
  addons/gdUnit4/test/core/GdUnitTestSuiteScannerTest.gd
Labels: refactoring, UI

#545 GD-544: Add Spy support for `Callable`
  addons/gdUnit4/src/core/GdFunctionDoubler.gd
  addons/gdUnit4/src/core/GdObjects.gd
  addons/gdUnit4/src/core/GdUnitClassDoubler.gd
  addons/gdUnit4/src/core/parse/GdScriptParser.gd
  addons/gdUnit4/src/doubler/CallableDoubler.gd
  addons/gdUnit4/src/mocking/GdUnitMockFunctionDoubler.gd
  addons/gdUnit4/src/spy/GdUnitSpyBuilder.gd
  addons/gdUnit4/src/spy/GdUnitSpyFunctionDoubler.gd
  addons/gdUnit4/test/core/GdUnitClassDoublerTest.gd
  addons/gdUnit4/test/core/discovery/GdUnitTestDiscoverGuardTest.gd
  addons/gdUnit4/test/core/parse/GdScriptParserTest.gd
  addons/gdUnit4/test/mocker/GdUnitMockerTest.gd
  addons/gdUnit4/test/spy/ClassWithEnumConstructor.gd
  addons/gdUnit4/test/spy/GdUnitSpyBuilderTest.gd
  addons/gdUnit4/test/spy/GdUnitSpyCallableTest.gd
  addons/gdUnit4/test/spy/GdUnitSpyTest.gd
Labels: enhancement

#547 GD-546: Allow to test un-typed values by `assert_that`
  addons/gdUnit4/src/GdUnitFloatAssert.gd
  addons/gdUnit4/src/GdUnitIntAssert.gd
  addons/gdUnit4/src/GdUnitTestSuite.gd
  addons/gdUnit4/src/asserts/GdAssertMessages.gd
  addons/gdUnit4/src/asserts/GdUnitArrayAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitFloatAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitIntAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitVectorAssertImpl.gd
  addons/gdUnit4/test/asserts/GdUnitVariantAssertThatTest.gd
  addons/gdUnit4/test/ui/parts/InspectorProgressBarTest.gd
Labels: enhancement
