Repository MikeSchulze/gdUnit4, pull requests merged in 2025-03, with the labels that each got.

#696 GD-695: Update documentation regarding find_child for C#
  _advanced_testing/scene_runner/accessors.md
Labels: documentation

#691 GD-635: Introduce `GdUnitTestReporter` interface and rework on `HTML` and `JUNIT` report generation
  .github/workflows/ci-dev.yml
  .github/workflows/ci-pr-publish-report.yml
  .github/workflows/ci-pr.yml
  .github/workflows/gdlint.yml
  addons/gdUnit4/plugin.gd
  addons/gdUnit4/src/core/GdUnitSingleton.gd
  addons/gdUnit4/src/core/discovery/GdUnitTestDiscoverGuard.gd
  addons/gdUnit4/src/core/runners/GdUnitTestCIRunner.gd
  addons/gdUnit4/src/reporters/GdUnitConsoleTestReporter.gd
  addons/gdUnit4/src/reporters/GdUnitHtmlTestReporter.gd
  addons/gdUnit4/src/reporters/GdUnitTestReporter.gd
  addons/gdUnit4/src/reporters/JUnitXmlReport.gd
  addons/gdUnit4/src/reporters/XmlElement.gd
  addons/gdUnit4/src/reporters/html/GdUnitByPathReport.gd
  addons/gdUnit4/src/reporters/html/GdUnitHtmlPatterns.gd
  addons/gdUnit4/src/reporters/html/GdUnitHtmlReport.gd
  addons/gdUnit4/src/reporters/html/GdUnitReportSummary.gd
  addons/gdUnit4/src/reporters/html/GdUnitTestCaseReport.gd
  addons/gdUnit4/src/reporters/html/GdUnitTestSuiteReport.gd
  addons/gdUnit4/src/reporters/html/template/css/breadcrumb.css
  addons/gdUnit4/src/reporters/html/template/css/logo.png
  addons/gdUnit4/src/reporters/html/template/css/logo.png.import
  addons/gdUnit4/src/reporters/html/template/css/styles.css
  addons/gdUnit4/src/reporters/html/template/folder_report.html
  addons/gdUnit4/src/reporters/html/template/index.html
  addons/gdUnit4/src/reporters/html/template/suite_report.html
  addons/gdUnit4/src/ui/GdUnitConsole.gd
  addons/gdUnit4/test/GdUnitTestSuiteTest.gd
  addons/gdUnit4/test/core/GdUnitSingletonTest.gd
  addons/gdUnit4/test/core/discovery/GdUnitTestDiscoverGuardTest.gd
  addons/gdUnit4/test/reporters/JUnitXmlReportTest.gd
  addons/gdUnit4/test/reporters/XmlElementTest.gd
Labels: Exclude from release nodes

#706 GD-635: Update .NET dependencies to gdUnit4Net v4.4.0 release candidate
  .editorconfig
  addons/gdUnit4/src/dotnet/GdUnit4CSharpApi.cs
  addons/gdUnit4/test/dotnet/ExampleTestSuite.cs
  addons/gdUnit4/test/dotnet/GdUnit4CSharpApiTest.cs
  gdUnit4.csproj
Labels: Exclude from release nodes

#716 Update ci-pr-publish-report.yml to work with `dorny/test-reporter@v2`
  .github/workflows/ci-pr-publish-report.yml
  .github/workflows/ci-pr.yml
Labels: Exclude from release nodes

#719 GD-686: Add `--godot_bin` argument and Godot .NET detection to test-runners scripts
  addons/gdUnit4/runtest.cmd
  addons/gdUnit4/runtest.sh
Labels: enhancement

#720 Fix `Parse Error: Identifier "GdUnitTestResourceLoader" not declared …
  addons/gdUnit4/src/core/GdUnitTestResourceLoader.gd
Labels: Exclude from release nodes
