Repository MikeSchulze/gdUnit4, pull requests merged in 2025-09, with the labels that each got.

#891 GD-887: Fixes run C# tests under linux by runtest script do not find any tests
  addons/gdUnit4/runtest.cmd
  addons/gdUnit4/runtest.sh
  addons/gdUnit4/src/core/runners/GdUnitTestSessionRunner.gd
  addons/gdUnit4/src/dotnet/GdUnit4CSharpApi.cs
  addons/gdUnit4/src/dotnet/GdUnit4CSharpApiLoader.gd
  addons/gdUnit4/test/dotnet/GdUnit4CSharpApiTest.cs
  gdUnit4.csproj
Labels: bug

#896 GD-878: Fixes verify a signal is NOT emitted twice by using argument matchers
  addons/gdUnit4/src/core/GdUnitSignalCollector.gd
  addons/gdUnit4/test/asserts/GdUnitSignalAssertImplTest.gd
Labels: bug

#915 GD-905: Convert base assert function is_equal to abstract (part3)
  addons/gdUnit4/src/GdUnitArrayAssert.gd
  addons/gdUnit4/src/GdUnitAssert.gd
  addons/gdUnit4/src/GdUnitBoolAssert.gd
  addons/gdUnit4/src/GdUnitDictionaryAssert.gd
  addons/gdUnit4/src/GdUnitFailureAssert.gd
  addons/gdUnit4/src/GdUnitFileAssert.gd
  addons/gdUnit4/src/GdUnitFloatAssert.gd
  addons/gdUnit4/src/GdUnitFuncAssert.gd
  addons/gdUnit4/src/GdUnitGodotErrorAssert.gd
  addons/gdUnit4/src/GdUnitIntAssert.gd
  addons/gdUnit4/src/GdUnitObjectAssert.gd
  addons/gdUnit4/src/GdUnitResultAssert.gd
  addons/gdUnit4/src/GdUnitSignalAssert.gd
  addons/gdUnit4/src/GdUnitStringAssert.gd
  addons/gdUnit4/src/GdUnitVectorAssert.gd
  addons/gdUnit4/src/asserts/GdUnitAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitDictionaryAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitFileAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitFloatAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitFuncAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitGodotErrorAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitIntAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitResultAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitSignalAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitStringAssertImpl.gd
Labels: refactoring, Exclude from release nodes

#901 GD-912: fix(delete_directory): Remove hidden files
  addons/gdUnit4/src/core/GdUnitFileAccess.gd
  addons/gdUnit4/src/update/GdUnitUpdate.gd
  addons/gdUnit4/test/core/GdUnitFileAccessTest.gd
Labels: bug

#918 GD-905: Convert base assert function append_failure_message to abstract (part6)
  addons/gdUnit4/src/GdUnitArrayAssert.gd
  addons/gdUnit4/src/GdUnitAssert.gd
  addons/gdUnit4/src/GdUnitBoolAssert.gd
  addons/gdUnit4/src/GdUnitDictionaryAssert.gd
  addons/gdUnit4/src/GdUnitFailureAssert.gd
  addons/gdUnit4/src/GdUnitFileAssert.gd
  addons/gdUnit4/src/GdUnitFloatAssert.gd
  addons/gdUnit4/src/GdUnitFuncAssert.gd
  addons/gdUnit4/src/GdUnitGodotErrorAssert.gd
  addons/gdUnit4/src/GdUnitIntAssert.gd
  addons/gdUnit4/src/GdUnitObjectAssert.gd
  addons/gdUnit4/src/GdUnitResultAssert.gd
  addons/gdUnit4/src/GdUnitSignalAssert.gd
  addons/gdUnit4/src/GdUnitStringAssert.gd
  addons/gdUnit4/src/GdUnitVectorAssert.gd
  addons/gdUnit4/src/asserts/GdUnitAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitBoolAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitDictionaryAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitFailureAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitFileAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitFloatAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitFuncAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitGodotErrorAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitIntAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitResultAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitSignalAssertImpl.gd
  addons/gdUnit4/src/asserts/GdUnitStringAssertImpl.gd
Labels: refactoring, Exclude from release nodes

#919 GD-905: Convert base assert function to abstract (part7)
  addons/gdUnit4/src/GdUnitArrayAssert.gd
  addons/gdUnit4/src/GdUnitBoolAssert.gd
  addons/gdUnit4/src/GdUnitDictionaryAssert.gd
  addons/gdUnit4/src/GdUnitFailureAssert.gd
  addons/gdUnit4/src/GdUnitFileAssert.gd
  addons/gdUnit4/src/GdUnitFloatAssert.gd
  addons/gdUnit4/src/GdUnitFuncAssert.gd
  addons/gdUnit4/src/GdUnitGodotErrorAssert.gd
  addons/gdUnit4/src/GdUnitIntAssert.gd
  addons/gdUnit4/src/GdUnitObjectAssert.gd
  addons/gdUnit4/src/GdUnitResultAssert.gd
  addons/gdUnit4/src/GdUnitSignalAssert.gd
  addons/gdUnit4/src/GdUnitStringAssert.gd
  addons/gdUnit4/src/GdUnitVectorAssert.gd
Labels: refactoring, Exclude from release nodes

#920 GD-903: Add support for variadic argument to assert_array
  .github/workflows/gdlint.yml
  addons/gdUnit4/src/GdUnitArrayAssert.gd
  addons/gdUnit4/src/asserts/GdUnitArrayAssertImpl.gd
  addons/gdUnit4/src/core/GdArrayTools.gd
  addons/gdUnit4/test/asserts/GdUnitArrayAssertImplTest.gd
Labels: enhancement

#922 GD-904: Add variadic argument support to `assert_dict`
  addons/gdUnit4/src/GdUnitDictionaryAssert.gd
  addons/gdUnit4/src/asserts/GdUnitDictionaryAssertImpl.gd
  addons/gdUnit4/test/asserts/GdUnitDictionaryAssertImplTest.gd
Labels: enhancement
